### PR TITLE
feat: Add permission callback

### PR DESCRIPTION
**Pull request by MichaelOrpheo**
### What
- Add callback to authorization status request.
### Why
- Useful to display a "warning" / "explanation" widget when user denied authorization.

### May be related to
- https://github.com/juliansteenbakker/mobile_scanner/issues/67

### CODE REVIEW

**Comment by martinhering** [comment]
+1

**Comment by martinhering** [comment]
A possible other solution would be, if `MobileScannerController` would not autostart anymore, we could invoke the start function manually and catch the `PlatformException` when state transitions to `MobileScannerState.denied`.

**Comment by teolemon** [comment]
Running "flutter pub get" in flutter_tools...                       4.0s
Changed lib/src/mobile_scanner.dart
Changed lib/src/mobile_scanner_controller.dart
Formatted 16 files (2 changed) in 0.45 seconds.
Formatting failed: 1

**Comment by teolemon** [comment]
And 2 merge conflicts to solve

**Pull request merged**
