### PR TITLE
Add integration tests for Android

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description
I'm trying to write an integration test for my app. I had some problems with so that, so I decided to first write an integration test for this package and then for my app because I know that the example app works :)

## Goal of the integration test
The goal of the integration test is to open the example app, scan the QR code and check if the result is correct. Currently, I'm just trying to write an integration test for Android.

### Code
```dart
  testWidgets(
    "scan qr code",
    (tester) async {
      await tester.pumpWidget(const MaterialApp(home: MyHome()));

      await tester.tap(find.text('MobileScanner with Controller'));
      await tester.pump();

      const link = 'https://sharez.one/pGmfH4rTQeuxXbLE6';
      try {
        await waitFor(
          tester,
          find.text(link),
          timeout: const Duration(seconds: 3),
        );
      } catch (e) {
        // When the test fails, the screenshot will be taken.

        // This is required prior to taking the screenshot (Android only).
        await binding.convertFlutterSurfaceToImage();

        // Trigger a frame.
        await tester.pump();
        await binding.takeScreenshot('screenshot-1');
      }

      expect(
        find.text(link),
        findsOneWidget,
      );
    },
  )
```

### Demo
https://user-images.githubusercontent.com/24459435/166640395-b6cdf631-3c51-454d-8158-b9adc158871f.mov

### Modify the virtual room of the emulator
The emulator has the option to open the camera in a virtual room. We need to insert an image into the room. Therefore, we are able to scan an QR code.

This is the image I inserted:

You can execute the following commands (working directory needs to be `example`) to insert the image into your virtual room (maybe you need to restart the emulator):
```sh
echo "" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
echo "poster qr_code" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
echo "size 2 2" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
echo "position 0 0.3 -1.0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
echo "rotation 0 0 0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
echo "default qr_code.jpg" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
mv integration_test/qr_code.jpg ~/Library/Android/sdk/emulator/resources/
```
Source: [Android emulator camera custom image](https://stackoverflow.com/a/64922184/8358501)

### Where should we run the integration test?
GitHub Actions would be a perfect solution to run the integration tests. We can build the app and execute the tests inside an emulator for free (because this package is open source).

```yaml
  integration-test:
    # Is recommended to run job with macOS to take advantage of hardware
    # acceleration support provided by HAXM.
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        api-level: [28, 31]
        # The package requires the PlayStore on the device.
        target: [playstore]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2.3.0
      - name: Run integration tests
        uses: nilsreichardt/android-emulator-runner@hot-fix-pre-emulator-launch-script
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back virtualscene -camera-front emulated
          working-directory: ./example
          pre-emulator-launch-script: |
            # Insert QR Code image from "integration_test/qr_code.jpg" into the Android
            # camera emulator.
            # 
            # Source: https://stackoverflow.com/a/64922184/8358501
            echo "" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "poster qr_code" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "size 2 2" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "position 0 0.3 -1.0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "rotation 0 0 0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            echo "default qr_code.jpg" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
            mv integration_test/qr_code.jpg ~/Library/Android/sdk/emulator/resources/
          script: |
            # We can't use the "flutter test" command, because it will not execute the adb
            # command to access the camera (defined in the "test_driver/integration_test.jpg")
            flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d emulator-5554
      - name: Upload failure screenshots
        uses: actions/upload-artifact@v1
        if: ${{ failure() || cancelled() }}
        with:
          name: emulator_configs_${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.api-level }}
          path: ./example/test_results
```

## Now my main problem
As you can see, the tests are working fine on my local machine (M1 MacBook). But when I try to execute the tests inside an emulator of GitHub Actions, the camera is just black. This is a screenshot of the emulator:

I don't know why. Technically, it should be possible to use the virtual room inside an GitHub Actions emulator. I wrote a small app, where I use the `camera` package, and it worked on all emulator:
image

You find here the screenshots (you need to download one of the zip files): https://github.com/nilsreichardt/playground/actions/runs/2266196738
Source code: https://github.com/nilsreichardt/playground/tree/android-emulator-camera (with GitHub Action & camera app)

My questions (cc @juliansteenbakker):
* Are you able to run the integration tests locally on your machine? `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart`
* Do you know why the camera is not starting on the GitHub Actions emulator?

You can use my fork: https://github.com/nilsreichardt/mobile_scanner/tree/integration-test
You can also see my changes in this PR: https://github.com/nilsreichardt/mobile_scanner/pull/1

You would be a big help, if you could help to fix these integration tests for the `mobile_scanner` library. Basically, the PR is already

### CODE REVIEW

**Comment by nilsreichardt** [comment]
Hmm, in a few times it's possible to open the virtual scene in the Android Emulator, but the QR code image is missing:
screenshot-1

Source: https://github.com/juliansteenbakker/mobile_scanner/actions/runs/2268650093

**Comment by juliansteenbakker** [comment]
There has been a lot of work in this PR, but for now it doesn't work and seems like no new work is being done, so i'm gonna close this to clean up the PR list. If someone wants to pick this up i'll reopen it.

**Comment by Clavum** [comment]
If this helps, the QR Code is missing because it's in a different room in the emulated environment. It's on the wall of the dining room (there's a doorway in the kitchen). Not sure how to move over there in an integration test though.

**Comment by nilsreichardt** [comment]
@Clavum The qr code should display at the front of the user, like it is the case in the demo (see PR description). In the GitHub workflow, I can set the coordinates.

**Pull request closed without merging**
