### PR TITLE
fix: Fixes issue #634

### PR DESCRIPTION
**Pull request by FlockiiX**
- This pull request implements a fix from issue https://github.com/juliansteenbakker/mobile_scanner/issues/634

### CODE REVIEW

**Comment by g0dzillaa** [comment]
Thanks for the PR. 

While this solves the buffer issue, this introduces a noticeable lag after a few seconds and skips a few frames resulting in a jank. I will see if I can get a screen recording.

**Comment by WilliBobadilla** [comment]
any news about this PR?

**Comment by g0dzillaa** [comment]
Any news on this merge? Can confirm this helps.

**Comment by FlockiiX** [comment]
Is the repository still being maintained?

**Comment by juliansteenbakker** [comment]
Sorry for the late response, LGTM!

**Pull request merged**
