### PR TITLE
feat: Support Dart 3

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR updates the maximum constraint to support Dart 3.

### CODE REVIEW

**Comment by teolemon** [comment]
info • Library directives without comments or annotations should be avoided • lib/mobile_scanner.dart:1:1 • unnecessary_library_directive
   info • Library directives without comments or annotations should be avoided • lib/mobile_scanner_web.dart:1:1 • unnecessary_library_directive
   info • Sort combinator names alphabetically • lib/src/web/utils.dart:3:18 • combinators_ordering
   info • 'setMockMethodCallHandler' is deprecated and shouldn't be used. Use tester.binding.defaultBinaryMessenger.setMockMethodCallHandler or TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler instead. Pass the channel as the first argument. This feature was deprecated after v3.9.0-19.0.pre • test/mobile_scanner_test.dart:10:[13](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/5058457848/jobs/9078604897?pr=639#step:7:14) • deprecated_member_use
   info • 'setMockMethodCallHandler' is deprecated and shouldn't be used. Use tester.binding.defaultBinaryMessenger.setMockMethodCallHandler or TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler instead. Pass the channel as the first argument. This feature was deprecated after v3.9.0-19.0.pre • test/mobile_scanner_test.dart:16:13 • deprecated_member_use

**Comment by navaronbracke** [comment]
I am aware of the analysis failures here. However, since this change only touches the pubspec, it should have not been flagged by the bot IMO.

**Comment by teolemon** [comment]
https://github.com/juliansteenbakker/mobile_scanner/pull/651

**Comment by teolemon** [comment]
I'm not proficient enough to validate the merge (especially for potential side effects). I'm just doing light gardening at my technical level.
Please look at Julian's call for help https://github.com/juliansteenbakker/mobile_scanner/issues/652

**Comment by navaronbracke** [comment]
For the version bump, it is explained here: https://dart.dev/resources/dart-3-migration#unversioned-vs-versioned-changes

See also the "Backwards compatibility" a bit lower on that page.

**Comment by navaronbracke** [comment]
@teolemon Apparently using Dart 3 works without bumping the upper constraint.

I can resolve dependencies using
```
Dart SDK version: 3.0.2 (stable) (Tue May 23 08:26:58 2023 +0000) on "macos_x64"
```
on the current master branch

**Pull request closed without merging**
