### PR TITLE
optionally return image with barcode

### PR DESCRIPTION
**Pull request by elliots**
New controller option `returnImage`. When set to true a UInt8List containing the latest frame is returned with the `barcode` event.

example app menu showing new option
example app showing returned image

Good things:
 - Seems to work. 

Bad things:
 - iOS only
 - Returned image is JPEG at 0.8 compression only
 - Often get a blurry frame back. Good enough to scan, not great for verification. Not sure what could be done about that, if anything.

Things that could be added:
  - Configurable image compression, resizing, format
  - Helper method to crop the image using the `corners` to return just the barcode.

See: #251

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
@elliots Is this PR ready to merge, or are you still working on it?

**Comment by elliots** [comment]
It's working for me, but it's also the first bit of swift I've written. And there's no android version. So, up to you.

**Comment by elliots** [comment]
I've rebased and fixed the lint issue.

**Comment by juliansteenbakker** [comment]
I am working on fixing this for android, so what i want to do is merge and once i got the android side working publish it as a new version. Thanks for your work !

**Comment by elliots** [comment]
No worries, thankyou for your work! I'm all done.

**Comment by robman70** [comment]
Hi, when is the release of the new version (with this new feature) planned?

Thank you

**Pull request merged**
