### PR TITLE
fix: Invalid argument: Instance of 'Ratio'

### PR DESCRIPTION
**Pull request by Apologiz**
fix: Unhandled Exception: Invalid argument: Instance of 'Ratio'

### CODE REVIEW

**Comment by teolemon** [comment]
@Apologiz : merge conflict + small linting issue
Run flutter analyze
Analyzing mobile_scanner...                                     

  error • The property 'index' can't be unconditionally accessed because the receiver can be 'null' • lib/src/mobile_scanner_controller.dart:176:51 • unchecked_use_of_nullable_value

1 issue found. (ran in 17.2s)
Error: Process completed with exit code 1.

**Comment by juliansteenbakker** [comment]
Thank you for your contribtion, but ratio has been removed in the latest version so this is no longer an issue.

**Comment by Hauglid** [comment]
Which version is that? It's still "available" in 2.1.0 but crashes the app.

**Comment by juliansteenbakker** [comment]
Version 3.0.0-beta.4. Will release a stable version next week after some testing.

**Pull request closed without merging**
