### PR TITLE
feat: Add overlay to scanner

### PR DESCRIPTION
**Pull request by svenopdehipt**
This PR adds an option to add an overlay to the scanner which is only visible when the scanner has started.

### CODE REVIEW

**Comment by svenopdehipt** [comment]
Is something wrong with this pull request?

**Comment by richard457** [comment]
@juliansteenbakker, please help in merging this PR.

**Comment by navaronbracke** [comment]
@richard457 The only thing this PR does is wrap the mobile scanner widget in a stack, so I don't see the benefit of this PR.

**Comment by svenopdehipt** [comment]
@navaronbracke this pr adds the option to add an overlay to the scanner which is only shown when there is no error and the scanner isn't loading

**Comment by richard457** [comment]
Yes, I guess that is what was needed in qr_code_scanner we had which we were able to use like
```dart
QRView(
        key: qrKey,
        onQRViewCreated: (controller) {
          _onQRViewCreated(controller, model);
        },
        overlay: QrScannerOverlayShape(
            borderColor: const Color(0xFF375778),
            borderRadius: 10,
            borderLength: 30,
            borderWidth: 10,
            cutOutSize: scanArea),
        onPermissionSet: (ctrl, p) => _onPermissionSet(context, ctrl, p),
      )
```

**Comment by richard457** [comment]
is there another way we can achieve the same?[navaronbracke](https://github.com/navaronbracke)

**Pull request closed without merging**
