### PR TITLE
Scan region

### PR DESCRIPTION
**Pull request by thamarakshan-pilla**
Hi, I have added the scan region which is customizable through user input arguments. It is enabled by default and can be disabled by the user. Please check it out and approve this PR because I really like this mobile scanner and I was planning on implementing it in one of my projects but the only thing it is missing is this scan region :)

Issue reference : #11 

Here is a screenshot of the scan region with the default values
Screenshot_1651964641
 
This is my first ever open source contribution soo I'm sorry if I have made any mistakes.
Thank you for this plugin :)

### CODE REVIEW

**Comment by thamarakshan-pilla** [comment]
I have only added this feature for non web option

**Comment by WingCH** [comment]
1. It seems that only the UI part, If the qrcode is outside the scanarea, `onDetect` will still trigger

https://user-images.githubusercontent.com/19588517/167277283-9e071ada-6487-4ad3-b834-9cb1ee6749e3.mov

2.  scanarea ui size should not be affected by MobileScanner's BoxFit 

image

Screenshot_20220508-090237

**Comment by casvanluijtelaar** [comment]
this is not what is requested in the issue. The issue describes a way to clip the input image before sending it to the detector. In my opinion the package should never include a pre made overlay widget.

**Comment by juliansteenbakker** [comment]
Thank you for your contribution. I'm on vacation right now till 23 of may. I will check and merge when i'm back.

**Comment by juliansteenbakker** [comment]
It seems that this PR only adds an overlay to the view, but does not restrict this. I think if we would implement this, we should also restrict the scan area, otherwise this would not make any sense to me.

**Comment by casvanluijtelaar** [comment]
> It seems that this PR only adds an overlay to the view, but does not restrict this. I think if we would implement this, we should also restrict the scan area, otherwise this would not make any sense to me.

absolutely I would even argue against an integrated overlay.

**Comment by juliansteenbakker** [comment]
I'm closing this for now, but feel free to reopen this once improvements has been made.

**Pull request closed without merging**
