### PR TITLE
fix: widget-disposed-during-start

### PR DESCRIPTION
**Pull request by EArminjon**
If mobile_scanner widget is disposed while start the following exception appear : 

```
flutter: Once you have called dispose() on a MobileScannerController, it can no longer be used.
flutter: #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
flutter: #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
flutter: #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:412:27)
flutter: #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
flutter: #4      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:277:7)
```

### CODE REVIEW

**Comment by EArminjon** [comment]
(added exception example)

**Comment by nishalsehan** [comment]
Can you please fix this issue asap.

**Comment by navaronbracke** [comment]
Good catch, we only had a check in the catch block it seems. Can you increment to patch version and update the changelog?

**Review by navaronbracke — APPROVED** [review]

**Comment by EArminjon** [comment]
@navaronbracke  done :)

**Comment by navaronbracke** [comment]
I will look into publishing this fix later today.

**Pull request merged**
