### PR TITLE
feat: Mobile scanner platform interface

### LINKED ISSUE #401: [feature] Convert the plugin to use `plugin_platform_interface`
Currently the plugin provides support for Android, iOS, MacOS and web.
However, the current implementation mixes `Texture` & `HTMLElementView` [directly in the implementation](https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/mobile_scanner.dart#L140-L142)
This can be improved by migrating the plugin to use the platform interface way of doing things.

This would also make implementing https://github.com/juliansteenbakker/mobile_scanner/issues/14 a bit easier, since only the windows implementation needs to be set up using the PlatformInterface method

TODO:
- [ ] introduce a platform interface
    - [ ] Widget buildScannerView()
    - [ ] The `MobileScannerArguments` class should be private, as it exposed implementation details
- [ ] reimplement web using `package:web`, which replaces `dart:html`
    - [ ] provide a web specific API to switch between barcode readers
    - [ ] migrate to Dart 3.3 extension types (currently not possible)
    - [ ] bring the camera handling improvements to the web    - [ ] start should throw if there is no camera
       - [ ] start should handle invalid camera direction in case the direction is not available
       - [ ] start should handle the torch state if the torch is not available
       - [ ] stop should do nothing if there is no camera
       - [ ] toggleTorch should do nothing if the current camera (if any) does not have a torch
- [ ] deprecate `hasTorch` and introduce a new `unavailable` torch mode
- [ ] remove lifecycle handling from the plugin, as it leads to lifecycle bugs #691 
   - [ ] remove the autoStart parameter
   - [ ] remove the deprecated onPermissionSet parameter
   - [ ] remove the `onStart` & `onScannerStarted` parameters
- [ ] refactor the `toggleTorch()`, `resetZoomScale()`, `setZoomScale()`, `stop()` methods to return instead of throw if the camera is null

### LINKED ISSUE #691: Improve Widget MobileScanner
I think we should remove AppLifecycleState. Because when we navigate to a certain screen and that screen requires permission, the app's lifecycle will run. This becomes inconvenient when the user keeps their phone near the QR Code, as it will reactivate the camera and trigger scanning, leading to logical errors even though the user is on a screen without the Mobile Scanner Widget.

My desire is to leave AppLifecycleState for the developers to handle, as it provides more flexibility rather than having the Widget itself handle it.

If I misunderstood any part, please kindly help me. Thank you for your assistance.

Screen Shot 2023-07-14 at 01 56 03

https://github.com/juliansteenbakker/mobile_scanner/assets/64881072/fd4d40f3-6c13-4972-b1bf-72541a3c7696

### LINKED ISSUE #699: call start() while already started
Tengo este error call start() while already started

### LINKED ISSUE #728: [Proposal] Have `analyzeImage` return the detected barcode
_This issue is a feature request to have the analyzeImage method return the barcode, rather than a boolean_

Sorry, if this is a dump question. But I can analyze a qrcode file image to determine if contains qrcode or not but I can't seem to extract the code or text embedded in the qrcode file image analyzed

### LINKED ISSUE #732: Golden tests error
Hello everyone, I doing golden tests and Im getting multiple errors, this is the widget:
(im using the version 3.0.0)
`class ScanWidget extends StatelessWidget {
  const ScanWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final scanRectSize = MediaQuery.of(context).size.width * 0.6;

    final mobileScannerController = MobileScannerController(
      facing: CameraFacing.back,
      torchEnabled: false,
    );

    return Stack(
      alignment: Alignment.center,
      children: [
        MobileScanner(
          controller: mobileScannerController,
          onDetect: (capture) async {
            await mobileScannerController.stop();
            final result = await context
                .read<TagOnBoardingCubit>()
                .checkScannedCode(capture.barcodes.first);
            if (result != null) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(result),
                ),
              );
              await Future.delayed(Duration(seconds: 2));
              mobileScannerController.start();
            }
          },
        ),
        Positioned.fill(
          child: Container(
            decoration: ShapeDecoration(
              shape: ScanOverlayShape(
                borderColor: Colors.white,
                borderRadius: 10,
                borderLength: scanRectSize / 4,
                borderWidth: 5,
                cutOutSize: scanRectSize,
              ),
            ),
          ),
        ),
        Positioned(
          left: MediaQuery.of(context).size.width * 0.05,
          top: MediaQuery.of(context).size.height * 0.1,
          child: IconButton(
            padding: EdgeInsets.zero,
            constraints: BoxConstraints(),
            icon: const Icon(Icons.close, color: Colors.white),
            onPressed: () => Navigator.of(context).pop(),
          ),
        ),
        Positioned(
          top: MediaQuery.of(context).size.height * 0.1,
          child: Row(
            children: [
              Text(
                S.of(context).scanTag.toUpperCase(),
                style: tagOnBoardingBoldText.copyWith(color: Colors.white),
              ),
            ],
          ),
        ),
        Positioned(
          top: MediaQuery.of(context).size.height * 0.16,
          child: Row(
            children: [
              /// Scan button
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(6)),
                  color: Colors.white,
                ),
                child: Column(
                  children: [
                    tagOnBoardingQrCodeAsset,
                    SizedBox(height: 8),
                    Text(
                      S.of(context).scan.toUpperCase(),
                      style: tagOnBoardingSmallText.copyWith(
                          color: secondaryTextColor),
                    ),
                  ],
                ),
              ),
              SizedBox(width: MediaQuery.of(context).size.height * 0.05),

              ///Nfc Button
              InkWell(
                onTap: () =>
                    BlocProvider.of<TagOnBoardingCubit>(context).changeToNfc(),
                child: Container(
                  padding: EdgeInsets.all(8),
                  child: Column(
                    children: [
                      tagOnBoardingContactlessAsset,
                      SizedBox(height: 8),
                      Text(
                        S.of(context).nfc.toUpperCase(),
                        style: tagOnBoardingSmallText.copyWith(
                            color: Colors.white),
                      ),
                    ],
                  ),
                ),
              ),
              SizedBox(width: MediaQuery.of(context).size.height * 0.05),

              /// Type button
              InkWell(
                onTap: () =>
                    BlocProvider.of<TagOnBoardingCubit>(context).changeToType(),
                child: Container(
                  padding: EdgeInsets.all(8),
                  child: Column(
                    children: [
                      tagOnBoardingNumPadAsset,
                      SizedBox(height: 8),
                      Text(
                        S.of(context).type.toUpperCase(),
                        style: tagOnBoardingSmallText.copyWith(
                            color: Colors.white),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
`

this is my golden test
`void main() {
  final TestWidgetsFlutterBinding binding =
      TestWidgetsFlutterBinding.ensureInitialized();

  group('scan tagOnboarding screen Golden Test', () {
    for (GoldenTheme theme in GoldenTheme.values) {
      for (GoldenScale scale in GoldenScale.values) {
        for (PhysicalSize physicalSizeDevices in PhysicalSize.values) {
          testWidgets('scan tagOnboarding page', (WidgetTester tester) async {
            // change screen size and pixel density ratio
            binding.window.physicalSizeTestValue =
                physicalSizeDevices.physicalSizes;
            binding.window.devicePixelRatioTestValue = 1.0;

            await loadAppFonts();
            final MockSessionCubit sessionCubit = MockSessionCubit();

            // create the mocks
            // use them in the sessionCubit stubbing
            await pumpWithSettle(
              tester,
              GoldenApp(
                theme: theme,
                scale: scale,
                child: BlocProvider<SessionCubit>(
                  create: (context) => sessionCubit,
                  child: ScanWidget(),
                  
                ),
              ),
            );

            await expectLater(
              find.byType(ScanWidget),
              matchesGoldenFile(
                'goldens/notifications_${scale.name}_${theme.name}_${physicalSizeDevices.name}.png',
              ),
            );
          });
        }
      }
    }
  });
}
`

I get this errors:

`The following _CastError was thrown running a test:
type 'MissingPluginException' is not a subtype of type 'MobileScannerException' in type cast

When the exception was thrown, this was the stack:
#0      _MobileScannerState._startScanner.<anonymous closure>.<anonymous closure> (package:mobile_scanner/src/mobile_scanner.dart:138:35)
#1      State.setState (package:flutter/src/widgets/framework.dart:1133:30)
#2      _MobileScannerState._startScanner.<anonymous closure> (package:mobile_scanner/src/mobile_scanner.dart:137:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 24 frames from dart:async and package:stack_trace)`

`══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 1146 pos 12: 'inTest': is not true.

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding.clock (package:flutter_test/src/binding.dart:1146:12)
#3      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:673:40)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:672:27)
#8      pumpWithSettle (file:///Users/andrecoelho/Desktop/projectToPrinter/mobile-app/test/custom_widget_pump.dart:39:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)`

`══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method updateScanWindow on channel
dev.steenbakker.mobile_scanner/scanner/method)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  scan tagOnboarding page`

### LINKED ISSUE #853: Using multiple `MobileScanner`s in a `PageTransitionSwitcher`
I got into the scenario where I would like to use multiple different `MobileScanner` Widgets one after the other, and I would like to transition between one scanner and the other using a `PageTransitionSwitcher`:
https://pub.dev/documentation/animations/latest/animations/PageTransitionSwitcher-class.html

Which works by keeping both children alive until the old one has left the screen, after which it is disposed. Obviously, this is a problem, because we can only have the camera open once at any time.

I tried to call `controller.close()` on the `MobileScannerController` (and awaiting it) before triggering the transition. This seems to prevent the `errorBuilder` from triggering, but the camera does not show in the second scan view. I also tried to disable `autoOpen` and instead open the scanner manually (also closing it manually as before), but this also did not work for me.

This issue occurs for me both on Android (Pixel 6, Pixel 7) as well as on iOS (iPhone XR, iPhone 14 Pro)

If I just replace the Widget in the widget tree, it works as expected. Is there some way I can manage the lifecycle of the `MobileScanner` such that I can prevent this behavior?

## Some logs
For the examples below, I show only the logs I think are relevant.
<details><summary>Default case</summary>

In this case, the first time the camera is shown as expected. I dispose the `controller` in the Widget's `dispose` method (which triggers at the end of the transition). The second time the camera is not shown, and I see the error builder instead (black screen with small white exclamation mark)

```
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED

<-- This is where I trigger the transition

W/1.raster(15811): type=1400 audit(0.0:5539): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app:s0:c111,c257,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=nl.evoit.lmsdriver
D/DeferrableSurface(15811): surface closed,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@d422dda
D/DeferrableSurface(15811): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@3ecab01
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Use cases [androidx.camera.core.Preview-6ed4b90f-1b65-4018-bc6b-459bacd2cbb996226249, androidx.camera.core.ImageAnalysis-52278297-5b21-481e-a876-06c019b51f3c112833230] now DETACHED for camera
D/UseCaseAttachState(15811): All use case: [] for camera: 0
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Resetting Capture Session
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Releasing session in state OPENED
D/UseCaseAttachState(15811): Active and attached use case: [] for camera: 0
D/UseCaseAttachState(15811): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
```
</details>

<details><summary>Close in dispose</summary>

In this case, the first time the camera is shown as expected too. I still dispose the `controller` in the Widget's `dispose` method (which triggers at the end of the transition). Now I call and await `controller.stop()` before triggering the transition. In the second view, I do not see the error builder, but I also do not see the camera view.

Judging from the logs, it seems to open and immediately close again...

```
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED

<-- This is where I call controller.stop()
<-- This is where I trigger the transition

D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
```
</details>

### LINKED ISSUE #894: Check if controller is started
I wish I could check if my MobileScannerController is started or not, before calling controller.start() and running into an Exception.

Something like the snip below:
```
if(controller.isStarted){
// Call controller.start() would result in Exception
 return;
} else {
 controller.start();
}
```

### PR DESCRIPTION
**Pull request by navaronbracke**
Update: the issue with the constructor was fixed at HEAD in the Dart SDK. We have to wait until it gets cherry-picked into stable before landing this.

This PR refactors the mobile_scanner package to use the new `plugin_platform_interface`.

This refactor brings along a bunch of improvements, but also some breaking changes that make the public API easier to work with.

Breaking changes:
- The plugin no longer manages the lifecycle of the controller. This avoids many of the reported issues when the MobileScanner widget is reparented in the widget tree. As a result the related API for starting the scanner has been removed. This includes the API for `onPermissionSet`, `autoStart`, `onStart`, `onScannerStarted` and `startDelay`.
- A MobileScannerController is now required for the MobileScanner widget, per the above change.
- The `onDetect` method has been removed. Instead, listen to the `barcodes` stream of the controller.
- The `overlay` widget of the `MobileScanner` has been replaced by a new property, `overlayBuilder`, which provides the constraints for the overlay.
- The `hasTorch` getter has been removed. Instead, the `TorchState` now has a new value for the unavailable state.
- The `MobileScannerState` enum has been renamed to `MobileScannerAuthorizationState`, as the name `MobileScannerState` is now reserved for the model of the ChangeNotifier. See the entry in the improvements.
- The `formats` attribute of the `MobileScannerController` is now non-null. The new default value is an empty list, which is treated as all possible formats.
- The analyzeImage method now returns an instance of `BarcodeCapture?`, instead of a boolean.
- The `cameraFacingOverride` argument for the `MobileScannerController.start()` method has been renamed to `cameraDirection` to better reflect its use.
- The class `MobileScannerArguments` has been removed. Instead, use the properties in `MobileScannerState`.
- The `raw` property of a `BarcodeCapture` is now `Object?` instead of `dynamic`, so that it participates in type promotion (whereas the dynamic type did not)
- The `width` and `height` of `BarcodeCapture` have been removed, in favor of the `size` property.
- The web implementation now uses ZXing by default. Adding a newer version of JSQr can be added in the future.

Improvements:
- The `MobileScannerController` is now a ChangeNotifier, with `MobileScannerState` as its model. This consolidates all the different value notifiers into one place.
- Flutter 3.16.0 is now required.
- The web implementation has been refactored away from `dart:html` and now uses the new JS static interop / package:web. This refactor enables some extra features for the web in the future (Dart extension types, support for zoom scale / camera selection)
- The web implementation now forwards the current torch mode & zoom scale to the controller. Implementing set/reset zoom & toggle torch is for another PR ;)

Fixes #401
Fixes #699
Fixes #691
Fixes #853
Fixes #894
Fixes #728
Fixes #732

### CODE REVIEW

**Comment by navaronbracke** [comment]
@juliansteenbakker Finally managed to finish my work for the platform interface. There are a lot of changes, so if you could review these that would be great. If possible we can release this refactor as a beta release, to allow for some testing and bugfixes.

**Comment by utamori** [comment]
@navaronbracke 

thank you

I have tried the example on Andoroid, but I continue to get `already open` error when I try to launch the camera many times at high speed.

**Comment by navaronbracke** [comment]
@utamori What is your use case for trying to open the camera many times at high speed?

When starting or stopping the camera, either method needs some time to do its work.
Forcing the camera to do this in quick succession quite probably results in race conditions, which is what you are seeing.

Therefor I do not specifically recommend that approach. You could try awaiting the `Future` that is returned by start, before attempting to `stop()` the camera?

**Comment by navaronbracke** [comment]
> When adding a camera scanning feature to a legacy app designed with the assumption of a physical scanner, users attempt to > work at the same speed as the physical scanner, causing this issue.
> Scanning a large number of product barcodes one after another.

Is there _really_ a need to start/stop the scanner multiple times in this case? You could keep the scanner started and listen to the barcodes event stream. I don't know how your app works, but I assume that when the user leaves the scanning page, the scanner is stopped by your code that handles navigating away from the page?

> Invoking .stop and .start with ErrorBuilder successfully restarts the camera.

The `errorBuilder` argument in itself does not "restart" the camera, it only displays the error that happened after the `start()` call finished. Could you provide a code sample to explain what you do in your error builder to restart the scanner? Then I can see if I can make this work here as well.

> I'm having difficulty understanding the suggestion. Could you please provide a more detailed explanation?

I meant to await the call to start (and/or stop), like this:

```dart
// Grab the start Future when starting the controller.
Future<void>? startFuture = controller.start();

// Before stopping, await the start Future, so that the controller does not end up in an undetermined state.
await startFuture;
await controller.stop();
```

**Comment by utamori** [comment]
> Could you provide a code sample to explain what you do in your error builder to restart the scanner? 

I referred to the following comment.

https://github.com/juliansteenbakker/mobile_scanner/issues/539#issuecomment-1469793176
```dart
errorBuilder: (context, error, child) {
controller.stop();
controller.start();
return ScannerReloadingWidget(error: error);
}
```

**Comment by navaronbracke** [comment]
@juliansteenbakker This PR is ready for review.

It is rather large, as it converts the entire `mobile_scanner` plugin to the plugin_platform_interface mechanism.
To make that possible, I had to make some breaking changes in this version (I had to rewrite some internals of the plugin).

I would gladly discuss the changes in this PR in person (virtually though). Could we schedule a meeting together to get this release landed? Since this PR doesn't add _everything_ that used to be in the plugin (I plan to add the missing features!) I opted to use a beta release.

**Comment by utamori** [comment]
Any update ?

**Comment by navaronbracke** [comment]
I'll prepare this PR as a beta release today.

After that, I'll work on getting the remaining features in, in subsequent beta releases for this version.
Once those are all finished we can look into promoting this version to a stable release.

I also want to add tests for things, but I still need to figure that out (although I do think, once we have a basic test set, adding more tests will be easier).

**Comment by navaronbracke** [comment]
@utamori I will be releasing the first version 5.0.0 beta shortly.

I will file a new issue for the remaining work (including WASM support)

**Pull request merged**
