### PR TITLE
feat(web): add zxing-js barcode reader

### PR DESCRIPTION
**Pull request by p-mazhnik**
Closes https://github.com/juliansteenbakker/mobile_scanner/issues/54

Replace `jsqr` library with [zxing-js](https://github.com/zxing-js/library) for full barcode support.  

As I mentioned in the [issue comment](https://github.com/juliansteenbakker/mobile_scanner/issues/54#issuecomment-1107658953), `qr-scanner` (https://github.com/nimiq/qr-scanner) is also limited to QR codes. 

I saw suggestions to use `html5-qrcode` (https://github.com/mebjas/html5-qrcode) in the issue but their API does not allow barcode decoding by providing the stream / video element directly to the API. They only work with an HTML element's `id`, which we can't use because the HTML element isn't connected to the HTML DOM yet, when we start decoding. And actually `html5-qrcode` library is a wrapper over `zxing-js`.

And this PR provides good abstractions so it will be easier to change smth later if needed.

PR features:
- abstract readers-related code to a separate `WebBarcodeReaderBase` class and mixins
- provide developers an ability to use their own reader by extending `WebBarcodeReaderBase` class and overriding `barCodeReader` property in `MobileScannerWebPlugin`
- we can still use `jsQR` library. 
Overriding example:
```dart
void main() {
  if (kIsWeb) {
    MobileScannerWebPlugin.barCodeReader =
        JsQrCodeReader(videoContainer: MobileScannerWebPlugin.vidDiv);
  }
  runApp(const MaterialApp(home: MyHome()));
}
```
- This PR adds `zxing-js` as a default library, but we can change it back to `jsQR`, keeping PR changes.

Note that I plan to take a look at torch support as a next step (different PR)

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
Thank you for all the PR's! I don't have time anymore this week to check and test it all, but i will make sure to check these next week.

**Comment by MB175** [comment]
looking forward to that :D

**Comment by p-mazhnik** [comment]
@MB175 
Did you add 
```html
<script type="text/javascript" src="https://unpkg.com/@zxing/library@0.19.1"></script>
```
to your index.html?

**Comment by MB175** [comment]
> @MB175 Did you add
> 
> ```
> <script type="text/javascript" src="https://unpkg.com/@zxing/library@0.19.1"></script>
> ```
> 
> to your index.html?

Thanks, works :D

Stupid mistake on my side

**Comment by juliansteenbakker** [comment]
Wow, great work! LGTM!

**Pull request merged**
